INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Almeria','2015-2016','2ª',30,19,'False','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Leganes','2015-2016','2ª',45,2,'True','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Mirandes','2015-2016','2ª',39,8,'False','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Zaragoza','2015-2016','2ª',42,6,'False','True','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Llagostera','2015-2016','2ª',18,22,'False','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Osasuna','2015-2016','2ª',36,12,'False','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Oviedo','2015-2016','2ª',45,4,'False','True','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Lugo','2015-2016','2ª',42,7,'False','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Huesca','2015-2016','2ª',36,13,'False','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Alaves','2015-2016','2ª',45,3,'False','True','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Gimn. Tarragona','2015-2016','2ª',48,1,'True','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Albacete','2015-2016','2ª',27,20,'False','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Numancia','2015-2016','2ª',39,10,'False','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Tenerife','2015-2016','2ª',30,17,'False','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Ath. Bilbao B','2015-2016','2ª',18,21,'False','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Girona','2015-2016','2ª',33,14,'False','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Ponferradina','2015-2016','2ª',33,16,'False','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Elche','2015-2016','2ª',39,11,'False','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Alcorcon','2015-2016','2ª',33,15,'False','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Mallorca','2015-2016','2ª',30,18,'False','False','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Cordoba','2015-2016','2ª',45,5,'False','True','False','False','False');
INSERT INTO Jornada(numero, nomEquipo, anyos, liga, puntos,puesto,asciende,playoff,desciende,champions,europa) VALUES (24,'Valladolid','2015-2016','2ª',39,9,'False','False','False','False','False');
