INSERT INTO Tiene(equipo, estadio) VALUES ('Camp Nou','Barcelona');
INSERT INTO Tiene(equipo, estadio) VALUES ('Santiago Bernabeu','Real Madrid');
INSERT INTO Tiene(equipo, estadio) VALUES ('Metropolitano','At. Madrid');
INSERT INTO Tiene(equipo, estadio) VALUES ('Benito Villamari­n','Betis');
INSERT INTO Tiene(equipo, estadio) VALUES ('Mestalla','Valencia');
INSERT INTO Tiene(equipo, estadio) VALUES ('San Mames','Ath. Bilbao');
INSERT INTO Tiene(equipo, estadio) VALUES ('Ramon Sanchez Pizjuan','Sevilla');
INSERT INTO Tiene(equipo, estadio) VALUES ('Anoeta','Real Sociedad');
INSERT INTO Tiene(equipo, estadio) VALUES ('RCDE Stadium','Espanyol');
INSERT INTO Tiene(equipo, estadio) VALUES ('Manuel Marti­nez Valero','Elche');
INSERT INTO Tiene(equipo, estadio) VALUES ('La Romareda','Zaragoza');
INSERT INTO Tiene(equipo, estadio) VALUES ('Riazor','Dptivo. Coruna');
INSERT INTO Tiene(equipo, estadio) VALUES ('Gran Canaria','Univ. Las Palmas');
INSERT INTO Tiene(equipo, estadio) VALUES ('Nueva Condomina','Murcia');
INSERT INTO Tiene(equipo, estadio) VALUES ('Balaidos','Celta');
INSERT INTO Tiene(equipo, estadio) VALUES ('Carlos Tartiere','Oviedo');
INSERT INTO Tiene(equipo, estadio) VALUES ('La Rosaleda','Malaga (C.D.)');
INSERT INTO Tiene(equipo, estadio) VALUES ('El Molinon','Sporting Gijon');
INSERT INTO Tiene(equipo, estadio) VALUES ('Jose Rico Perez','Hercules');
INSERT INTO Tiene(equipo, estadio) VALUES ('Jose Zorrilla','Valladolid');
INSERT INTO Tiene(equipo, estadio) VALUES ('Ciudad de Valencia','Levante');
INSERT INTO Tiene(equipo, estadio) VALUES ('Ramon de Carranza','Cadiz');
INSERT INTO Tiene(equipo, estadio) VALUES ('Son Moix','Mallorca');
INSERT INTO Tiene(equipo, estadio) VALUES ('Estadio de la Ceramica','Villarreal');
INSERT INTO Tiene(equipo, estadio) VALUES ('Heliodoro Rodri­guez Lopez','Tenerife CD');
INSERT INTO Tiene(equipo, estadio) VALUES ('Nuevo Los Carmenes','Granada');
INSERT INTO Tiene(equipo, estadio) VALUES ('El Sardinero','Rac. Santander');
INSERT INTO Tiene(equipo, estadio) VALUES ('Nuevo Arcangel','Cordoba');
INSERT INTO Tiene(equipo, estadio) VALUES ('Nuevo Colombino','Rec. Huelva');
INSERT INTO Tiene(equipo, estadio) VALUES ('Chapin','Xerez/Xerez FC');
INSERT INTO Tiene(equipo, estadio) VALUES ('Mendizorroza','Alaves');
INSERT INTO Tiene(equipo, estadio) VALUES ('El Sadar','Osasuna');
INSERT INTO Tiene(equipo, estadio) VALUES ('Balear','Baleares CD');
INSERT INTO Tiene(equipo, estadio) VALUES ('Carlos Belmonte','Albacete');
INSERT INTO Tiene(equipo, estadio) VALUES ('Coliseum Alfonso Perez','Getafe');
INSERT INTO Tiene(equipo, estadio) VALUES ('Las Gaunas','Logrones');
INSERT INTO Tiene(equipo, estadio) VALUES ('Nuevo Vivero','Badajoz');
INSERT INTO Tiene(equipo, estadio) VALUES ('Castalia','Castellon');
INSERT INTO Tiene(equipo, estadio) VALUES ('Mini Estadi','Barcelona B');
INSERT INTO Tiene(equipo, estadio) VALUES ('Cartagonova','Cartagena');
INSERT INTO Tiene(equipo, estadio) VALUES ('Juegos Mediterraneos','Almeria');
INSERT INTO Tiene(equipo, estadio) VALUES ('Estadio de Vallecas','Rayo Vallecano');
INSERT INTO Tiene(equipo, estadio) VALUES ('Romano','Merida');
INSERT INTO Tiene(equipo, estadio) VALUES ('Nou Estadi de Tarragona','Gimn. Tarragona');
INSERT INTO Tiene(equipo, estadio) VALUES ('Camp d'Esports','Lleida');
INSERT INTO Tiene(equipo, estadio) VALUES ('Reino de Leon','Cult. Leonesa');
INSERT INTO Tiene(equipo, estadio) VALUES ('Municipal de Montilivi','Girona');
INSERT INTO Tiene(equipo, estadio) VALUES ('San Lazaro','Compostela');
INSERT INTO Tiene(equipo, estadio) VALUES ('La Victoria','Jaen');
INSERT INTO Tiene(equipo, estadio) VALUES ('Butarque','Leganes');
INSERT INTO Tiene(equipo, estadio) VALUES ('El Planti­o','Burgos CF');
INSERT INTO Tiene(equipo, estadio) VALUES ('A Malata','Ferrol');
INSERT INTO Tiene(equipo, estadio) VALUES ('Pasaron','Pontevedra');
INSERT INTO Tiene(equipo, estadio) VALUES ('Nova Creu Alta','Sabadell');
INSERT INTO Tiene(equipo, estadio) VALUES ('Francisco de la Hera','Extremadura');
INSERT INTO Tiene(equipo, estadio) VALUES ('Oli­mpic de Terrassa','Terrassa');
INSERT INTO Tiene(equipo, estadio) VALUES ('Linarejos','Linares');
INSERT INTO Tiene(equipo, estadio) VALUES ('Municipal de Vilatenim','Figueres');
INSERT INTO Tiene(equipo, estadio) VALUES ('Nuevo Los Pajaritos','Numancia');
INSERT INTO Tiene(equipo, estadio) VALUES ('Jose del Cuvillo','Portuense');
INSERT INTO Tiene(equipo, estadio) VALUES ('El Torali­n','Ponferradina');
INSERT INTO Tiene(equipo, estadio) VALUES ('Ipurua','eibar');
INSERT INTO Tiene(equipo, estadio) VALUES ('Francisco Artes Carrasco','Lorca');
INSERT INTO Tiene(equipo, estadio) VALUES ('Luis Suiñer','Palencia');
INSERT INTO Tiene(equipo, estadio) VALUES ('Pepico Amat','Eldense CD');
INSERT INTO Tiene(equipo, estadio) VALUES ('Viejo Nervion','Sevilla At');
INSERT INTO Tiene(equipo, estadio) VALUES ('Ciudad de Puertollano','Calvo Sotelo');
INSERT INTO Tiene(equipo, estadio) VALUES ('Lasesarre','Barakaldo');
INSERT INTO Tiene(equipo, estadio) VALUES ('Angel Carro','Lugo');
INSERT INTO Tiene(equipo, estadio) VALUES ('El Alcoraz','Huesca');
INSERT INTO Tiene(equipo, estadio) VALUES ('Antonio Domi­nguez Alfonso','Marino CD');
INSERT INTO Tiene(equipo, estadio) VALUES ('Nuevo Mirador','Algeciras');
INSERT INTO Tiene(equipo, estadio) VALUES ('Municipal de Marbella','Marbella');
INSERT INTO Tiene(equipo, estadio) VALUES ('Pri­ncipe Felipe','Cacereno');
INSERT INTO Tiene(equipo, estadio) VALUES ('Narci­s Sala','Sant Andreu');
INSERT INTO Tiene(equipo, estadio) VALUES ('Alfonso Murube','Ceuta');
INSERT INTO Tiene(equipo, estadio) VALUES ('Nuevo Malecon','Torrelavega');
INSERT INTO Tiene(equipo, estadio) VALUES ('Pedro Escarti­n','Guadalajara');
INSERT INTO Tiene(equipo, estadio) VALUES ('Alfredo Di Stefano','Castilla CF');
INSERT INTO Tiene(equipo, estadio) VALUES ('Anduva','Mirandes');
INSERT INTO Tiene(equipo, estadio) VALUES ('San Pablo','Ecija');
INSERT INTO Tiene(equipo, estadio) VALUES ('Nou Municipal de Palamos','Palamos/Llagostera');
INSERT INTO Tiene(equipo, estadio) VALUES ('Virgen de las Nieves','Tenisca SD');
INSERT INTO Tiene(equipo, estadio) VALUES ('O Couto','Ourense');
INSERT INTO Tiene(equipo, estadio) VALUES ('Nuevo Roman Suarez Puerta','Aviles CF');
INSERT INTO Tiene(equipo, estadio) VALUES ('Salto del Caballo','Toledo');
INSERT INTO Tiene(equipo, estadio) VALUES ('Santo Domingo','Alcorcon');
INSERT INTO Tiene(equipo, estadio) VALUES ('Stadium Gal','Real Union');
INSERT INTO Tiene(equipo, estadio) VALUES ('Miramar','Luanco');
INSERT INTO Tiene(equipo, estadio) VALUES ('Nuevo Silvestre Carrillo','Mensajero CD');
INSERT INTO Tiene(equipo, estadio) VALUES ('Camp Nou Municipal','Reus CD');
INSERT INTO Tiene(equipo, estadio) VALUES ('Municipal de Montilla','Montilla FC');
INSERT INTO Tiene(equipo, estadio) VALUES ('La Juventud','Xerez');
INSERT INTO Tiene(equipo, estadio) VALUES ('Artunduaga','Basconia CD');
INSERT INTO Tiene(equipo, estadio) VALUES ('La Condomina','UCAM');
INSERT INTO Tiene(equipo, estadio) VALUES ('Area Deportiva de Puente Castro','Cult. Leonesa');
INSERT INTO Tiene(equipo, estadio) VALUES ('Las Llanas','Sestao');
INSERT INTO Tiene(equipo, estadio) VALUES ('El Mazo','Haro CD');
INSERT INTO Tiene(equipo, estadio) VALUES ('Municipal de Badalona','Badalona');
INSERT INTO Tiene(equipo, estadio) VALUES ('Hermanos Antuiña','Caudal');
INSERT INTO Tiene(equipo, estadio) VALUES ('Nou Sardenya','Europa CD');
INSERT INTO Tiene(equipo, estadio) VALUES ('Merkatondoa','Izarra CD');
INSERT INTO Tiene(equipo, estadio) VALUES ('Los Arcos','Orihuela');
INSERT INTO Tiene(equipo, estadio) VALUES ('Cerro del Espino','Majadahonda');
INSERT INTO Tiene(equipo, estadio) VALUES ('Javier Sotomayor','Salamanca');
