INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Camp Nou','Barcelona',1957,99354);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Santiago Bernabeu','Real Madrid',1947,81044);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Metropolitano','At. Madrid',2017,67703);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Benito Villamari­n','Betis',1929,60721);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Cartuja','',1997,60000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Olimpico Lluis Companys','',1927,55926);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Mestalla','Valencia',1923,55000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('San Mames','Ath. Bilbao',2013,53289);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Ramon Sanchez Pizjuan','Sevilla',1958,43883);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Anoeta','Real Sociedad',1993,42000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('RCDE Stadium','Espanyol',2009,40500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Manuel Marti­nez Valero','Elche',1976,33732);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Romareda','Zaragoza',1957,33608);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Riazor','Dptivo. Coruna',1944,32911);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Gran Canaria','Univ. Las Palmas',2003,32392);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nueva Condomina','Murcia',2006,31179);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Balaidos','Celta',1928,31100);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Carlos Tartiere','Oviedo',2000,30500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Rosaleda','Malaga (C.D.)',1941,30044);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El Molinon','Sporting Gijon',1908,30000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Jose Rico Perez','Hercules',1974,29500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Jose Zorrilla','Valladolid',1982,26512);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Ciudad de Valencia','Levante',1969,25354);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Ramon de Carranza','Cadiz',1957,25033);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Son Moix','Mallorca',1999,24262);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Estadio de la Ceramica','Villarreal',1923,23500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Heliodoro Rodri­guez Lopez','Tenerife CD',1925,23000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nuevo Los Carmenes','Granada',1995,22369);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El Sardinero','Rac. Santander',1988,22222);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nuevo Arcangel','Cordoba',1993,21822);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nuevo Colombino','Rec. Huelva',2001,21670);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Chapin','Xerez/Xerez FC',1988,20486);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Mendizorroza','Alaves',1924,19840);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El Sadar','Osasuna',1967,19800);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Balear','Baleares CD',1960,18000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Carlos Belmonte','Albacete',1960,18000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Helmantico','',1970,17341);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Coliseum Alfonso Perez','Getafe',1998,17000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Las Gaunas','Logrones',2002,16000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nuevo Vivero','Badajoz',1998,15598);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Castalia','Castellon',1987,15500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Mini Estadi','Barcelona B',1982,15276);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Cartagonova','Cartagena',1988,15105);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Juegos Mediterraneos','Almeria',2004,15000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Estadio de Vallecas','Rayo Vallecano',1976,14708);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Romano','Merida',1953,14537);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nou Estadi de Tarragona','Gimn. Tarragona',1971,14500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El Soto','',1974,14000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Camp d'Esports','Lleida',1919,13500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Reino de Leon','Cult. Leonesa',2001,13451);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal de Montilivi','Girona',1970,13400);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Juan Rojas','',1976,13000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('San Lazaro','Compostela',1993,13000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Victoria','Jaen',2001,12600);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Butarque','Leganes',1998,12450);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El Planti­o','Burgos CF',1964,12200);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('A Malata','Ferrol',1993,12043);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Pasaron','Pontevedra',1956,12000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal','',1969,12000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nova Creu Alta','Sabadell',1967,11981);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Francisco de la Hera','Extremadura',1951,11580);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Oli­mpic de Terrassa','Terrassa',1960,11500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Ciudad de Tudela','',1969,11000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Ciudad de Malaga','',2006,10816);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Alvarez Claro','',1945,10000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Linarejos','Linares',1956,10000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nou Camp de Inca','',1964,10000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal de Vilatenim','Figueres',1986,9472);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nuevo Los Pajaritos','Numancia',1999,9025);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Murta','',1920,9000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Guillermo Amor','',1964,9000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Antonio Peroles','',2005,9000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Jose del Cuvillo','Portuense',1972,8600);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El Torali­n','Ponferradina',2000,8200);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Ipurua','eibar',1947,8127);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Francisco Artes Carrasco','Lorca',2003,8120);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Luis Suiñer','Palencia',1973,8100);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nueva Balastera','',2006,8070);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Francisco Peraza','',1923,8000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal El Val','',1947,8000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Pepico Amat','Eldense CD',1964,8000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Gerardo Salvador','',1971,8000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Viejo Nervion','Sevilla At',1974,8000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nou Camp de Sa Pobla','',1977,8000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal de San Miguel','',1986,8000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Iberoamericano 2010','',1992,8000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Ciudad de Puertollano','Calvo Sotelo',2010,8000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Lasesarre','Barakaldo',2001,7960);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Santo Domingo','',2001,7870);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Angel Carro','Lugo',1974,7840);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Ruta de la Plata','',2002,7813);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El Alcoraz','Huesca',1972,7638);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Polideportivo Municipal','',1983,7500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Antonio Domi­nguez Alfonso','Marino CD',1992,7500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nuevo Mirador','Algeciras',1999,7200);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Ciudad Deportiva de Lanzarote','',1968,7000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal de Marbella','Marbella',1975,7000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Pri­ncipe Felipe','Cacereno',1977,7000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Narci­s Sala','Sant Andreu',1970,6593);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Alfonso Murube','Ceuta',1933,6500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal Villanovense','',1992,6500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Estadi de la Feixa Llarga','',1999,6294);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nuevo Malecon','Torrelavega',1922,6007);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Guadalquivir','',1923,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Pedro Escarti­n','Guadalajara',1967,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Vicente Garci­a','',1971,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Albuera','',1977,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Alfredo Di Stefano','Castilla CF',2005,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Fuensanta','',2011,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El Prado','',1944,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Planilla','',1946,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Anduva','Mirandes',1950,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Alberto Fernandez','',1968,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Adolfo Suarez','',1976,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El Montecillo','',1977,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('San Pablo','Ecija',1986,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nou Municipal de Palamos','Palamos/Llagostera',1989,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Ciutat Esportiva Dani Jarque','',2001,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Virgen de las Nieves','Tenisca SD',2001,6000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('O Couto','Ourense',1948,5659);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Magdalena','',1949,5500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Arboleja','',1984,5500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nuevo Roman Suarez Puerta','Aviles CF',1999,5500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nuestra Seiñora de la Caridad','',1958,5500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Chamorro Marti­nez','',1970,5500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Polideportivo Municipal','',1976,5500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Ciudad Deportiva de Plasencia','',1982,5500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Los Corrales','',2013,5500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Salto del Caballo','Toledo',1973,5300);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Ciudad de Ayamonte','',2007,5200);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Santo Domingo','Alcorcon',1978,5100);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Ciudad Deportiva del Villarreal CF','',2002,5100);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Vicente Sanz','',1957,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal de Lucena','',1972,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El Mauli­','',1981,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Serratella','',2000,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Stadium Gal','Real Union',1926,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Constitucion','',1944,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El Palmar','',1948,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal de Tomelloso','',1948,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El Clariano','',1951,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Miramar','Luanco',1952,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Los Cuartos','',1953,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Pinilla','',1957,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal de Deportes','',1966,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Escribano Castilla','',1970,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nuevo Estadio','',1972,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal Navalmoral de la Mata','',1972,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nuevo Silvestre Carrillo','Mensajero CD',1977,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Camp Nou Municipal','Reus CD',1978,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal de Montilla','Montilla FC',1981,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Mundial 82','',1984,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nou Municipal','',1994,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Bobila','',1995,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Juventud','Xerez',2001,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Artunduaga','Basconia CD',2007,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Ciudad Deportiva Municipal','',2007,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal de Alcazar ','',2007,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Baltar','',2012,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Orellana','',2003,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Gazitaguada','',2005,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Fernando Torres','',2011,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal','',2003,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Ciudad Deportiva','',1999,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Manuel Calzado Galvan','',2020,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Santa Ana ','',2009,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Isidro Calderon','',2006,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El olivar','',2007,5000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Condomina','UCAM',1924,4600);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Area Deportiva de Puente Castro','Cult. Leonesa',1998,4600);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Estadi Municipal de Can Misses','',1991,4500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Mati­as Prats','',1934,4500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Las Llanas','Sestao',1923,4367);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El Mazo','Haro CD',2004,4300);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal de Badalona','Badalona',2017,4170);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Hermanos Antuiña','Caudal',1951,4000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nou Sardenya','Europa CD',1995,4000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El Rubial','',1913,4000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Estadio El Carmen Sariinena','',1960,4000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Merkatondoa','Izarra CD',1928,3500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Los Arcos','Orihuela',1945,3500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('As Eiroas','',2001,3500);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Cerro del Espino','Majadahonda',1995,3376);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Guillermo Olagiue','',1967,3259);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('El Pilar','',1922,3000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Pepe Orti­z','',1995,3000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Pepe Gonicalvez','',1938,3000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Javier Sotomayor','Salamanca',1970,2400);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal de Ejea','',2010,2223);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Mina','',1916,2000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Espiguera','',1917,2000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Municipal de Guijuelo','',1970,2000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Nuevo San Bartolome','',1982,2000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('Vicente del Bosque','',2013,2000);
INSERT INTO Estadio(nombre, nomEquipo, inaguracion, capacidad) VALUES ('La Hoya','',1981,2000);
