INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Rec. Huelva','Real Club Recreativo de Huelva',1889,'Huelva');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES (' Sevilla','Sevilla Futbol Club',1890,'Sevilla ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Ath. Bilbao','Athletic Club ',1898,'Bilbao');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Palamos','Palamos Club de Futbol',1898,'Palomos');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Barcelona','Futbol Club Barcelona ',1899,'Barcelona ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Espanyol','Real Club Deportivo Espanol',1900,'Barcelona ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Real Madrid','Real Madrid Club de Futbol',1900,'Madrid ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Sabadell','Centre dEsports Sabadell Futbol Club ',1901,'Sabadell');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('At. Madrid','Club Atletico de Madrid ',1903,'Madrid ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Badalona','Club de Futbol Badalona',1903,'Badalona');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Aviles CF','Real Aviles Club de Futbol ',1903,'Aviles');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Vilafranca FC','Futbol Club Vilafranca ',1904,'Vilafranca del Penedès ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Sporting Gijon','Real Sporting de Gijon',1905,'Gijon');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Santfeliuenc FC','Santfeliuenc Futbol Club',1905,'Sant Feliu de Llobregat ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Beasain SD','Sociedad Deportiva Beasain',1905,'Beasain');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Carabanchel CD','Real Club Deportivo Carabanchel',1906,'Madrid');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Dptivo. Coruna','Real Club Deportivo de La Coruna',1906,'La Coruna ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Europa CD','Club Esportiu Europa',1907,'Barcelona ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Betis','Real Betis Balompie',1907,'Sevilla ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Torrelavega','Gimnastica de Torrelavega',1908,'Torrrelavega');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Murcia','Real Murcia Club de Futbol',1908,'Murcia ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Algeciras','Algeciras Club de Futbol',1909,'Algeciras ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Guecho','Arenas Club de Guecho',1909,'Guecho');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Reus CD','Club de Futbol Reus Deportiu',1909,'Reus');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Portugalete','Club Portugalete ',1909,'Portugalete');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Levante','Levante Union Deportiva',1909,'Valencia ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Real Sociedad','Real Sociedad de Futbol',1909,'San Sebastian ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Cadiz','Cadiz Club de Futbol',1910,'Cadiz ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Tenerife CD','Club Deportivo Tenerife',1912,'Santa Cruz de Tenerife ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Luarca CF','Luarca Club de Futbol',1912,'Luarca');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Linense','Real Balompedica Linense',1912,'La Linea ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Gara CD','Real Club Deportivo Gara',1912,'Garachico');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Titanico','Real Titanico',1912,'Pola de Laviana');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Icodense UD','Union Deportiva Icodense',1912,'Tenerife');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Basconia CD','Club Deportivo Basconia',1913,'Basauri');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Rac. Santander','Real Racing Club de Santander',1913,'Santander ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Deusto SD','Sociedad Deportiva Deusto',1913,'Deusto');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Gimn. Tarragona','Club Gimnàstic de Tarragona',1914,'Tarragona');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Haro CD','Club Haro Deportivo',1914,'Haro');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Hercules','Hercules de Alicante Club de Futbol',1914,'Alicante');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Coruna CD','Real Club Deportivo de La Coruna B',1914,'La Coruna');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Cayon CF','Club Deportivo Cayon',1915,'Santa Maria de Cayon');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Real Union','Real Union Club',1915,'Irun');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Tenerife','Real Union de Tenerife Club de Futbol',1915,'Tenerife');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Erandio SD','Sociedad Deportiva Erandio Club',1915,'Erandio');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Lealtad CD','Club Deportivo Lealtad',1916,'Villaviciosa');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Siero','Club Siero',1916,'Pola de Siero');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Mallorca','Real Club Deportivo Mallorca',1916,'Palma de Mallorca ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Barakaldo','Barakaldo Club de Futbol',1917,'Baracaldo ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Contestano CD','Club Deportivo Contestano',1917,'Cocentaina');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Elgoibar CD','Club Deportivo Elgoibar',1917,'Elgoibar');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Pilonesa','Deportiva Pilonesa',1917,'Infiesto');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Pumarin CF','Pumarin Club de Futbol',1917,'Oviedo');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Alicante','Alicante Club de Futbol',1918,'Alicante');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Caudal','Caudal Deportivo',1918,'Mieres');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Santutxu FC','Santutxu Futbol Club',1918,'Santutxu ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Cartagena F.C.','Cartagena Futbol Club',1919,'Cartagena ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Acero CD','Club Deportivo Acero',1919,'Puerto de Sagunto');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Castellon','Club Deportivo Castellon',1919,'Castellon de la Plana ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Cacereno','Club Polideportivo Cacereno',1919,'Caceres');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Ferrol','Racing Club de Ferrol',1919,'Ferrol ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Durango SD','Sociedad Cultural Deportiva de Durango',1919,'Durango');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Lutxana','Sporting Club de Lutxana',1919,'Baracaldo');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Figueres','Unio Esportiva Figueres',1919,'Figueras ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Valencia','Valencia Club de Futbol',1919,'Valencia ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Osasuna','Club Atletico Osasuna',1920,'Pamplona ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Baleares CD','Club Deportivo Atletico Baleares',1920,'Palma de Mallorca');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Capellades CF','Club Futbol Capellades',1920,'Capellades');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Eldense CD','Club Deportivo Eldense ',1921,'Elda ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Alaves','Deportivo Alaves',1921,'Vitoria ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Ponferradina','Sociedad Deportiva Ponferradina',1921,'Ponferrada ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Mensajero CD','Club Deportivo Mensajero ',1922,'Santa Cruz de La Palma ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Elche','Elche Club de Futbol',1922,'Elche ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Gernika SD','Sociedad Deportiva Gernika Club ',1922,'Gernika ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Tenisca SD','Sociedad Deportiva Tenisca ',1922,'Santa Cruz de La Palma ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Tolosa CF','Tolosa Club de Futbol ',1922,'Tolosa ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Velez CF','Velez Club de Futbol ',1922,'Velez-Malaga ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Astur CF','Astur Club de Futbol ',1923,'Oviedo ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Cult. Leonesa','Cultural y Deportiva Leonesa',1923,'Leon ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Celta','Real Club Celta de Vigo',1923,'Vigo ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Izarra CD','Club Deportivo Izarra ',1924,'Estella ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Rayo Vallecano','Rayo Vallecano de Madrid',1924,'Madrid ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Amorebieta SD','Sociedad Deportiva Amorebieta ',1925,'Vizcaya ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Sant Andreu','Unio Esportiva Sant Andreu',1925,'Barcelona ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Oviedo','Real Oviedo',1926,'Oviedo ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Mirandes','Club Deportivo Mirandes',1927,'Miranda de Ebro ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Calavera CF','Calavera Club de Futbol ',1928,'Sevilla ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Carrion','Carrion Balompie',1928,'Carrion de los Cespedes ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Alcoyano','Club Deportivo Alcoyano',1928,'Alcoy ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Leganes','Club Deportivo Leganes',1928,'Leganes ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Toledo','Club Deportivo Toledo',1928,'Toledo');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Portuense','Racing Club Portuense ',1928,'El Puerto de Santa Maria ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Valladolid','Real Valladolid Club de Futbol',1928,'Valladolid ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Jaen','Real Jaen Club de Futbol',1929,'Jaen ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Mollerusa','Club de Ftubol Joventut Mollerussa',1930,'Mollerussa');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Girona','Girona Futbol Club',1930,'Gerona ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Castilla CF','Real Madrid Castilla Club de Futbol ',1930,'Madrid');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Vetusta','Real Oviedo Vetusta ',1930,'Oviedo ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Luanco','Club Marino de Luanco ',1931,'Luanco');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Granada','Granada Club de Futbol',1931,'Granada ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Puerto CF','Puerto Real Club de Futbol ',1931,'Puerto Real ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Zaragoza','Real Zaragoza',1932,'Zaragoza ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Marino CD','Club Deportivo Marino ',1933,'Arona');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Ecija','Ecija Balompie',1939,'Ecija');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Albacete','Albacete Balompie',1940,'Albacete ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Pontevedra','Pontevedra Club de Futbol',1941,'Pontevedra ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Eibar','Sociedad Deportiva Eibar',1943,'Eibar ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Mestalla CF','Valencia Club de Futbol Mestalla ',1944,'Paterna');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Villarreal','Villarreal Club de Futbol',1944,'Villarreal ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Numancia','Club Deportivo Numancia de Soria',1945,'Soria ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Alzira','Union Deportiva Alzira',1946,'Alcira');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Guadalajara','Club Deportivo Guadalajara',1947,'Guadalajara ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Calvo Sotelo','Club Deportivo Puertollano ',1947,'Puertollano');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Granada CR','Club Recreativo Granada ',1947,'Granada ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Llagostera','Unio Esportiva Llagostera',1947,'Llagostera');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Xerez','Xerez Club Deportivo',1947,'Jerez de la Frontera ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Malaga','Malaga Club de Futbol',1948,'Malaga ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Univ. Las Palmas','Union Deportiva Las Palmas',1949,'Las Palmas ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Sevilla','Sevilla Atletico Club ',1950,'Sevilla');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Ourense','Club Deportivo Ourense',1952,'Orense');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Lugo','Club Deportivo Lugo',1953,'Lugo ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Cordoba','Cordoba Club de Futbol',1954,'Cordoba ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Ceuta','Club Atletico de Ceuta',1956,'Ceuta ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Ensidesa','Club Deportivo Ensidesa',1956,'Aviles');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Huesca','Sociedad Deportiva Huesca',1960,'Huesca ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Langreo','Union Popular de Langreo ',1961,'Langreo');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Vecindario','Union Deportiva Vecindario',1962,'Vecindario');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Atletico B','Club Atletico de Madrid B ',1963,'Majadahonda ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Athletic','Bilbao Athletic ',1964,'Lezama ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Logrones','Union Deportiva Logrones',1967,'Logrono ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Ejido','Club Deportivo Ejido',1969,'El Ejido');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Barcelona B FC','Futbol Club Barcelona B ',1970,'Barcelona ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Alcorcon','Agrupacion Deportiva Alcorcon',1971,'Alcorcon ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Montilla FC','Montilla Club de Futbol ',1973,'Montilla ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Palencia','Club de Futbol Palencia',1975,'Palencia');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Majadahonda FC','Club de Futbol Rayo Majadahonda ',1976,'Majadahonda ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Alboraya UD','Alboraya Union Deportiva ',1978,'Alboraya ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Getafe','Getafe Club de Futbol',1983,'Getafe ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Getafe B ','Getafe Club de Futbol B ',1983,'Getafe ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Burgos CF','Real Burgos Club de Futbol',1983,'Burgos ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Almeria  ','Union Deportiva Almeria',1989,'Almeria ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Orihuela','Orihuela Club de Futbol',1993,'Orihuela');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Burgos','Burgos Club de Futbol',1994,'Burgos ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Cartagena','Futbol Club Cartagena',1995,'Cartagena ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Lorca','Lorca Atletico Club de Futbol',1996,'Lorca');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Sestao','Sestao River Club',1996,'Sestao ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Marbella','Marbella Futbol Club',1997,'Marbella');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Alcorcon B','Agrupacion Deportiva Alcorcon B ',1998,'Alcorcon ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('UCAM','UCAM Murcia Club de Futbol ',1999,'Murcia ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Compostela','Sociedad Deportiva Compostela',2004,'Santiago de Compostela ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Extremadura','Extremadura Union Deportiva',2007,'Almendralejo ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Linares','Linares Deportivo',2009,'Linares');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Logrones SD','Sociedad Deportiva Logrones ',2009,'Logrono ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Terrassa','Tarrasa Olimpica 2010',2009,'Tarrasa');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Lleida','Club Lleida Esportiu',2011,'Lerida ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Badajoz','Club Deportivo Badajoz',2012,'Badajoz ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Merida','Merida Asociacion Deportiva',2013,'Merida ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Salamanca','Unionistas de Salamanca Club de Futbol',2013,'Salamanca ');
INSERT INTO Equipo(nombreCorto, nombreOficial, fundacion, ciudad) VALUES ('Xerez FC','Xerez Deportivo Futbol Club ',2013,'Jerez de la Frontera ');
